### ISSUE TITLE
Convert UDM Pro to qemu

### ISSUE THREAD

**Issue by claytondukes** [boostchicken/udm-utilities#131]
I'm curious - has anyone tried converting the UDM Pro's OS to a qemu image for testing?
I tried dd to another system we have (running Proxmox) but no dice.

Example (from UDM host):

```
dd bs=16M if=/dev/sdb | bzip2 -c | nc 192.168.1.14 19000
```

On receiver:

```
nc -l -p 19000 | bzip2 -d | dd bs=16M of=sdb.raw
```

Then it **should** be a simple matter of converting the raw to qcow2:

```
qemu-img convert -c -O qcow2 sdb.raw sdb.qcow2
```
But alas, no boot :)

**Comment by otkd** [comment]
Have you set hypervisor to emulate the correct arch? Also, why bother converting to qcow, raw should be fine?

**Comment by fabianishere** [comment]
I've tried this as well, but you probably won't be able to get any output. The kernel (and U-boot) used by the UDM Pro do not support (in their configuration) the UART implementation (PL011) and the generic PCI host controller provided by `qemu-aarch64`.

What you can do is run the root filesystem of the UDM Pro with a Linux kernel that supports these features (for instance, just take an ARM64 kernel from Ubuntu). However, you'll find that UbiOS will fail to boot since it cannot load some of its proprietary modules (`ubnthal`, `ubnt_common`, etc..)
