### ISSUE TITLE
Request: ntopng container

### ISSUE THREAD

**Issue by rodalpho** [boostchicken/udm-utilities#14]
Everybody knows Ubiquiti's built-in DPI metrics are hilariously useless. Any thoughts on adding an ntopng container? 

I would actually like to just run nprobe on the UDMP and then run the ntopng web UI on a separate box myself, but I imagine most people would prefer it self-contained.

https://github.com/ntop/ntopng

**Comment by boostchicken** [comment]
I know nothing of ntop, how does it hook into the OS/Kernel to get those stats?  Running a webserver is no problem. Getting it access to the right information might be a little more complex.  Can it just ssh into the UDM/P and run commands and get the data it needs?  Does it need access to the host main networking namespace?  I'll probably mess with it at some point soon, but the more info you give me up front the quicker I can probably get it done?

**Comment by boostchicken** [comment]
Just as a little side note, really anything that runs in Docker can run on the box,  for kicks I got a redis server and an openvpn server running.  If there is any interest on those I could publish it.  I don't publish everything I do because the community here has not stepped up much in terms of supporting each other, and I don't want to just throw it out there and hope for the best.

If more people want to help manage / develop / maintain this repo, i'd like that.

**Comment by magic2910** [comment]
Have anybody running a traefik container inside the udm-base? Would be perfect for letsencrypt certificates, or?
Any other ideas howto keep letsencrypt certificates after a reboot (for the guest portal)
And by the way: nice job!

**Comment by rodalpho** [comment]
They publish docker containers so it must work inside a container somehow.

https://github.com/ntop/docker-ntop

**Comment by boostchicken** [comment]
Looks like someone already did this
https://community.ui.com/questions/ntopng-for-the-UDM-UDM-PRO/87b051ff-0003-4d5b-bbdc-48f962617ee7

**Comment by rodalpho** [comment]
Great minds!

**Comment by boostchicken** [comment]
@rodalpho gonna close this.  I am working with the creator to get some info on it linked in this repo as well
