### ISSUE TITLE
Alternative to config.gateway.json

### ISSUE THREAD

**Issue by galvesribeiro** [boostchicken/udm-utilities#144]
Hello folks!

I've see that one of the common tools here allow some sort of custom startup/boot like init.d. I've just bought an UDM-Pro which I was looking to use https://github.com/basmeerman/unifi-usg-kpn to allow me to connect my IPTV to the UDM-Pro network seamlessly as this repo shown that was possible by using the config.gateway.json. 

Unlucky for me, the devices seems not support that file anymore...

So, do you guys know any alternatives to the config.gateway.json on the UDM-Pro that would help to achieve that use case?

Thank you!

**Comment by SturdyErde** [comment]
This repo is the closest thing we have to the functionality of the old json file. What are you going to accomplish? If you take a look at the readme and wiki, you'll probably find that someone has done it.

**Comment by galvesribeiro** [comment]
My ISP delivers IPTV and Internet (PPPoE) as separated VLANs (20 and 10 respectively) on the fiber connection. I have an GPON device from TP-Link that I connect on their Fiber link and connect the ethernet from it to the UDM WAN ethernet port.

On the repo I link on this issue, that guy makes those VLANs to be available on the single WAN connection by changing the config.gateway.jsjon which is not available. 

I've spent many days trying to figure out how to make that topology to work without requiring that file. I was able to get the internet working but not the IPTV. 

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/4714040/111247344-94c76580-85e6-11eb-9754-f55f4d0b0b63.png">

Both vlan10 and vlan20 are created as vlan-only on the Networks tab.

The STB device gets the IP address on the LAN but it doesn't boot into the IPTV streaming :/

The origina link on USG made those VLans directly on the LAN interface but since it isn't possible, I've tried to separate it physically over the UDM-Pro ports but it just doesn't work. I mean, internet works, the PPPoE connection works, but the IPTV doesn't :/

Any ideas?

Thanks!

**Comment by kalenarndt** [comment]
@boostchicken Here is an example of a user setting an MTU of 9000 on the L3 interface and on the physical interface. 

https://wesleygeelhoed.nl/2020/03/14/enable-jumbo-frames-on-ubiquiti-unifi-security-gateway-usg/

I wrote a shell script that actually sets the MTU to 9000 for all of my required interfaces but anytime a provision operation happens, the config is overwritten. 

`#!/bin/sh
interfaces=$(ip link list | grep -i switch | sed 's/^[^:]*://g; s/:.*//; s/@switch0.*//')
sfp=$(ip link list | grep -i eth10 | sed 's/^[^:]*://g; s/:.*//; s/@eth10.*//')
for interface in $interfaces
do
  echo $interface
  ip link set dev $interface mtu 9000
done

for sfp in $sfp
do
  echo $sfp
  ip link set dev $sfp mtu 9000
done`


Turns out that the UDM Pro doesn't allow you to use Jumbo Frames across the LAN SFP ports or the L3 interfaces for VLANs ....because why would they :D

**Comment by boostchicken** [comment]
Hey, closing this issue as it is solved by the udm kernel project.

https://github.com/fabianishere/udm-kernel-tools/blob/master/docs/iptv.md
