### ISSUE TITLE
On-boot-script stops working on 1.9

### ISSUE THREAD

**Issue by abmarine** [boostchicken/udm-utilities#168]
Hi 
Seems that the on boot script stopped working after 1.9 update?
I use the on boot script to disable NAT on a few UDMs for a couple of months but this week it stopped working after updating to 1.9 ?
Has anyone else experienced the same?
Andre

**Comment by ThirteenTX** [comment]
Did you try uninstalling it and re-installing it by chance after the update? Not sure if that is the fix, just a thought.

**Comment by pgorod** [comment]
@abmarine did reinstalling work for you?

I am about to install this for the first-time on a UDM 1.9.3, I'd like to know if I should expect problems or not. Thanks!

**Comment by BerziOnline** [comment]
Same problem here, since upgradinge the controller.
Removing the package and re-installing didn't fix the problem.
At the moment I think the udm-boot script has really no affect anymore.
It's definitely installed and the shell script behind for the nat rules is working fine and is also in the correct directory. 

In my opinion the udm-boot script from here isn't working correct at the moment with Controller Version 1.9.3 on UDM (non-pro).
I also have no solution for this right now.

**Comment by pgorod** [comment]
I got it working on the UDM 1.9.3 without any problems. It was a new install, not an upgrade...

**Comment by boostchicken** [comment]
@BerziOnline what problem are you seeing?

**Comment by BerziOnline** [comment]
@boostchicken the output gives:
`root@ubnt:/# journalctl -u udm-boot.service
-- Logs begin at Tue 2021-05-25 17:21:30 CEST, end at Tue 2021-05-25 19:04:42 CEST. --
-- No entries --
`
The general journal is full of errors in every second:
`May 25 17:32:40 ubnt avahi-daemon[62]: Registering new address record for fe80::f692:bfff:fe98:d7c4 on ra0.*.
May 25 17:32:40 ubnt avahi-daemon[62]: iface.c: avahi_server_add_address() failed: Not permitted
May 25 17:32:41 ubnt avahi-daemon[62]: Registering new address record for fe80::f692:bfff:fe98:d7c5 on rai0.*.
May 25 17:32:41 ubnt avahi-daemon[62]: iface.c: avahi_server_add_address() failed: Not permitted
`

But I never had a look before into the journal, so I'm not sure if it's relevant here.

**Comment by boostchicken** [comment]
@BerziOnline can you show me the output of "more /lib/systemd/system/udm-boot.service" from unifi-os

**Comment by BerziOnline** [comment]
@boostchicken Of course, thanks for checking.

`
root@ubnt:/# more /lib/systemd/system/udm-boot.service 
[Unit]
Description=Run On Startup UDM
After=network.target

[Service]
Type=oneshot
ExecStart=/sbin/ssh-proxy '/mnt/data/on_boot.sh'
RemainAfterExit=true
StandardOutput=journal

[Install]
WantedBy=multi-user.target
`

Just let me know, if I can serve more information.

**Comment by boostchicken** [comment]
@BerziOnline does /mnt/data/on_boot.sh exist in your UDM (not the unifi-os) and is it chmod +x.  

In all honesty you are pretty out of date, I would update to 1.0.5

**Comment by BerziOnline** [comment]
@boostchicken Yes, the script was there and was executable.
I noticed the following then:


> root@ubnt:/# systemctl status udm-boot               
>● udm-boot.service - Run On Startup UDM
>   Loaded: loaded (/lib/systemd/system/udm-boot.service; enabled; vendor preset: enabled)
>   Active: failed (Result: exit-code) since Tue 2021-05-25 06:47:35 CEST; 1 day 8h ago
> Main PID: 59 (code=exited, status=1/FAILURE)
>
>Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.


Then I followed your suggestion and updated now to 1.0.5.
Now there's no /mnt/data/on_boot.sh anymore, but I think it's correct because you listed that in the changelog.

After the install the systemctl status was fine and active of the service.
Then I rebooted once to test it again. The nat bash-script (executable in //mnt/data/on_boot.d/ and working if I start it) wasn't fired again after reboot. So I checked the systemctl status again and it's inactive again:


> root@ubnt:/# systemctl status udm-boot
>● udm-boot.service - Run On Startup UDM
>   Loaded: loaded (/lib/systemd/system/udm-boot.service; disabled; vendor preset: enabled)
>   Active: inactive (dead)


Here's the output for my actual version now you asked before:


> root@ubnt:/# more /lib/systemd/system/udm-boot.service 
>[Unit]
>Description=Run On Startup UDM
>Wants=network-online.target
>After=network-online.target
>
>[Service]
>Type=oneshot
>ExecStart=/sbin/ssh-proxy 'mkdir -p /mnt/data/on_boot.d && find -L /mnt/data/on_boot.d -iname "*.sh" -mindepth 1 -maxdepth 1 -type f -print0 | sort -z | xargs
> -0 -r -n 1 -- sh -c '\''if test -x "$0"; then echo "%n: running $0"; "$0"; else case "$0" in *.sh) echo "%n: sourcing $0"; . "$0";; *) >echo "%n: ignoring $0"
>;; esac; fi'\'
>RemainAfterExit=true
>
>[Install]
>WantedBy=multi-user.target


Starting the script by systemctl works fine and also executes the nat bash script.

**Comment by boostchicken** [comment]
that nat script is probably running too fast.  Impossible to know without looking at its contents but I am willing to guess its trying to delete stuff that just isnt there yet.  Anyways, closing the issue since its working now.
