### ISSUE TITLE
I can't run install on UdM 1.10.0

### ISSUE THREAD

**Issue by ltdstudio** [boostchicken/udm-utilities#218]
When I got 1.0.5 DEB file

> 

root@ubnt:~# dpkg -i udm-boot_1.0.5_all.deb
dpkg-deb: error: 'udm-boot_1.0.5_all.deb' is not a debian format archive
dpkg: error processing archive udm-boot_1.0.5_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
#-> ubnt-dpkg-cache install
<-# ubnt-dpkg-cache install
Errors were encountered while processing:
 udm-boot_1.0.5_all.deb

**Comment by allenbower** [comment]
Since the https://udm-boot.boostchicken.dev location wasn't available I had tried using the github URL and ran into this same issue. What I did as a workaround was download the .deb from github to my computer, and served the fila via TFTP using tftpd32 and changed the curl to: `curl -L tftp://<computer IP address>/udm-boot_1.0.5_all.deb -o udm-boot_1.0.5_all.deb`. Install went as expected after that.
