### ISSUE TITLE
Document how to upgrade a container

### ISSUE THREAD

**Issue by rodalpho** [boostchicken/udm-utilities#24]
I suggest documenting how to properly upgrade a container for newbies. This can be very brief, like:

1) Update container
podman pull docker.io/path/to/application

2) Stop old container and remove it
podman stop containername
podman rm containername

4) Start it back up
podman run -d ... (the full run line for that specific application)

**Comment by SturdyErde** [comment]
Is this kind of information best kept in the readme or the wiki?

**Comment by rodalpho** [comment]
I would suggest putting it in the wiki so it doesn't need to be updated for each individual container, then linking to that wiki article in each readme.

**Comment by boostchicken** [comment]
I think we should put this information in the wiki.  I believe the wiki is open for editing by the community, so feel free to add the documentation/discussion there.  

Stuff in the repo is generally for stuff that requires an experts review (happy to add other maintainers to this project if anyone is interested)

**Comment by rodalpho** [comment]
Sure, added here:

https://github.com/boostchicken/udm-utilities/wiki/HOWTO:-Upgrade-Containers

**Comment by JohnGalt1717** [comment]
It would be nice if this was automatic and checked periodically watchtower style.  Podman has this built in, but because systemd isn't running it doesn't work.  A script that did this that we could drop in that started up, checked, updated them, and then set a chron to do it daily, would be really nice.

(and I don't think you need to rm to update, you should just have to stop, pull, start)
