### ISSUE TITLE
Wireguard-go performance

### ISSUE THREAD

**Issue by Lollaskates** [boostchicken/udm-utilities#44]
You mentioned the reduced performance of wireguard due to having to use the go implementation rather than the kernel implementation. Is it possible to update the readme to contain some example performance metrics? The UDMP datasheet suggests IPSEC performance of 800mbps, what can wireguard-go achieve?

**Comment by SturdyErde** [comment]
I think the reason that wireguard-go is slower is simply due to the fact that it runs in the user space instead of natively in the kernel. Once in there, the performance comparison from one system to the next is probably even more likely to be impacted by environmental or configuration differences between any two systems. 

The performance between the kernel and go implementations has difference has been noted elsewhere. I wonder if it really makes sense to ask the owner of this repo to go into that level of detail on a project that they don't maintain. Does that make sense, or am I way off?

**Comment by SturdyErde** [comment]
Oh, that said--here's some performance comparisons that you can view right on the WireGuard project's site. It compares WireGuard to IPSec and OpenVPN, but does not include wireguard-go in the comparison. https://www.wireguard.com/performance/

**Comment by tusc** [comment]
I doubt you'll get anywhere near 800Mbps as IPSec is kernel based. Wireguard-go has to deal with context switches between userland and kernel mode which impacts performance. As a reference, I've ported boringtun, a Rust based userland implementation of Wireguard to the UDM and have acheived 500Mbps.

**Comment by Lollaskates** [comment]
thank you all for the information!

Closing
