### ISSUE TITLE
Docker container not starting.

### ISSUE THREAD

**Issue by joeblack2k** [boostchicken/udm-utilities#68]
Hello, i understand this is maybe not fair to put under issue. But i was hoping any of you guys could help me out.

i'm trying to start this docker: https://hub.docker.com/r/wernight/mopidy so i can throw audio at my UDM Base from Home Assistant (like a doorbell) i first tried a simple airplay docker and that worked so i was excited. unfortunately i'm getting stuck with this error:

docker run -d --name="mpd" -v /opt/config/mpd.conf:/etc/mpd.conf -v /etc/localtime:/etc/localtime:ro --device /dev/snd -p 6600:6600 -p 8800:8800 vimagick/mpd

ERRO[0000] Error adding network: failed to find plugin "loopback" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] 

ERRO[0000] Error while adding to cni lo network: failed to find plugin "loopback" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] 

does anyone know how to get this to run ?

thanks in advance!

**Comment by spali** [comment]
did you try ```--network host```? then no cni plugin is required and your containers ports are directly accessible on the udm network interface.

**Comment by SturdyErde** [comment]
I agree with your analysis that this should not be filed as an issue for this repo. :) 

Still, you might find the answer in your mpd.conf file. Since your docker start command does not specify a network type, it's probably in the conf file as 'loopback' instead of 'bridge'. Docker is not my strong point, but you may find some luck with that. You can also switch your `docker run` command to `podman run`.

**Comment by boostchicken** [comment]
Closing as it has nothing to do with this repo
